### ISSUE TITLE
Sharness self-test fails

### ISSUE THREAD

**Issue by rafasc** [chriscool/sharness#104]
3e0777c (test/sharness: normalize -x output before testing it, 2019-06-27)

was not enough to fix that failing test in my case.

The output I get is slightly different: `++ true`,

Applying the following would make the test pass.

``` diff
diff --git a/test/sharness.t b/test/sharness.t
index 7f720c3..bb53f38 100755
--- a/test/sharness.t
+++ b/test/sharness.t
@@ -307,10 +307,10 @@ test_expect_success 'pretend we have a pass, fail, and known breakage using -x'
                sed -e '/^ *$/d' >clean_out <out &&
                test_cmp expect_out clean_out &&
                sed -e 's/^> //' >expect_err <<-\\EOF &&
-               > +true
-               > +false
+               > ++ true
+               > ++ false
                > error: last command exited with \$?=1
-               > +false
+               > ++ false
                > error: last command exited with \$?=1
                EOF
                sed -e 's/^+ /+/' >clean_err <err &&
```

Maybe the normalization could be changed to `sed -e 's/^[+]+ /+/'`

The user choice of `$PS4` can also interfere with this test.

**Comment by chriscool** [comment]
Thanks for your report @rafasc! Please take a look at the above PR that should fix this issue.

You are right that `$PS4` interferes with the test. Maybe setting `$PS4` could help test this in a better way.

**Comment by rafasc** [comment]
Thanks for looking into it.

I still do not completely understand the underling issue here, and explicitly setting `PS4=+` (as in the suggestion I made on the PR) seems to change the behaviour again, making it print + 3 times. :roll_eyes:
